sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: af2f2f2fs
    accessKeySecret: asfdafad2
    bucketName: sky-take-out249
  redis:
    host: localhost
    port: 6379
    password: 123
    database: 10